# Generated by Django 4.2.4 on 2023-08-19 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmazingWebsite', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WebsiteTitle',
            new_name='Heading',
        ),
    ]
