# Generated by Django 4.2.4 on 2023-08-19 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmazingWebsite', '0002_rename_websitetitle_heading'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Heading',
            new_name='Website_Title',
        ),
    ]
