# Generated by Django 4.2.4 on 2023-08-19 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmazingWebsite', '0003_rename_heading_website_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='website_title',
            old_name='Website_Title',
            new_name='Title',
        ),
    ]
