# Generated by Django 4.2.4 on 2023-08-19 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmazingWebsite', '0004_rename_website_title_website_title_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Website_Title',
            new_name='Title',
        ),
    ]
