# Generated by Django 4.2.4 on 2023-08-19 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmazingWebsite', '0005_rename_website_title_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=5000)),
                ('HyperLink', models.CharField(blank=True, max_length=5000)),
            ],
        ),
    ]
