# Generated by Django 4.2.4 on 2023-08-19 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('high', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Other_Event',
            new_name='Event',
        ),
    ]
