# Generated by Django 4.2.4 on 2023-08-19 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('high', '0002_rename_other_event_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=1050)),
                ('Email', models.EmailField(blank=True, max_length=500)),
                ('Phone', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='concert',
            name='Director_Email',
        ),
        migrations.RemoveField(
            model_name='concert',
            name='Director_Phone_Number',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='Director_Email',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='Director_Phone_Number',
        ),
        migrations.RemoveField(
            model_name='event',
            name='Director_Email',
        ),
        migrations.RemoveField(
            model_name='event',
            name='Director_Phone_Number',
        ),
        migrations.AlterField(
            model_name='concert',
            name='Director_In_Charge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='high.director'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='Director_In_Charge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='high.director'),
        ),
        migrations.AlterField(
            model_name='event',
            name='Director_In_Charge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='high.director'),
        ),
    ]
