# Generated by Django 4.2.4 on 2023-08-19 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500)),
                ('job_title', models.CharField(blank=True, max_length=500)),
                ('work_number', models.CharField(blank=True, max_length=500)),
                ('alternate_number', models.CharField(blank=True, max_length=500)),
                ('work_email', models.CharField(blank=True, max_length=500)),
                ('alternate_email', models.CharField(blank=True, max_length=500)),
                ('work_address', models.TextField(blank=True, max_length=500)),
            ],
        ),
    ]
