# Generated by Django 4.2.4 on 2023-08-19 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_rename_name_contact_first_name_contact_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='alternate_email',
            field=models.EmailField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='contact',
            name='work_email',
            field=models.EmailField(blank=True, max_length=500),
        ),
    ]
