# Generated by Django 4.2.4 on 2023-08-19 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concert_name', models.CharField(blank=True, max_length=1050)),
                ('concert_date_and_time', models.DateTimeField(blank=True)),
                ('location_address', models.TextField(blank=True, max_length=5000)),
                ('notes', models.TextField(blank=True, max_length=5000)),
                ('Qualifying_Orchestras', models.TextField(blank=True, help_text='Which orchestras are involved/playing in this concert?', max_length=5000)),
                ('Director_In_Charge', models.CharField(blank=True, max_length=500)),
                ('Director_Email', models.EmailField(blank=True, max_length=500)),
                ('Director_Phone_Number', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest_name', models.CharField(blank=True, max_length=1050)),
                ('contest_date_and_time', models.DateTimeField(blank=True)),
                ('location_address', models.TextField(blank=True, max_length=5000)),
                ('notes', models.TextField(blank=True, max_length=5000)),
                ('Qualifying_Orchestras', models.TextField(blank=True, help_text='Which orchestras are involved/playing in this concert?', max_length=5000)),
                ('Director_In_Charge', models.CharField(blank=True, max_length=500)),
                ('Director_Email', models.EmailField(blank=True, max_length=500)),
                ('Director_Phone_Number', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(blank=True, max_length=1050)),
                ('event_date_and_time', models.DateTimeField(blank=True)),
                ('location_address', models.TextField(blank=True, max_length=5000)),
                ('notes', models.TextField(blank=True, max_length=5000)),
                ('Qualifying_Orchestras', models.TextField(blank=True, help_text='Which orchestras are involved/playing in this concert?', max_length=5000)),
                ('Director_In_Charge', models.CharField(blank=True, max_length=500)),
                ('Director_Email', models.EmailField(blank=True, max_length=500)),
                ('Director_Phone_Number', models.CharField(blank=True, max_length=500)),
            ],
        ),
    ]
