# Generated by Django 4.2.4 on 2023-08-19 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZZDev', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bootstrap',
            old_name='CSS',
            new_name='CSS_Href',
        ),
        migrations.RenameField(
            model_name='bootstrap',
            old_name='JS',
            new_name='CSS_Script',
        ),
        migrations.AddField(
            model_name='bootstrap',
            name='JS_Script_1',
            field=models.TextField(default='NotAvailable'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bootstrap',
            name='JS_Script_2',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
