# Generated by Django 4.2.4 on 2023-08-19 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZZDev', '0002_rename_css_bootstrap_css_href_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bootstrap',
            old_name='CSS_Script',
            new_name='CSS_Integrity',
        ),
        migrations.AddField(
            model_name='bootstrap',
            name='CSS_Script_Integrity',
            field=models.TextField(default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bootstrap',
            name='CSS_Script_Source',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bootstrap',
            name='JS_Script_1_Integrity',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bootstrap',
            name='JS_Script_2_Integrity',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
